version: '3'
services:
  # Database
  db:
    image: mysql:8.0.32
    restart: always
    # Lưu trữ db ngoài container
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      # Tạo 1 database ant_home
      MYSQL_DATABASE: ant_home
    ports:
      - '3306:3306'
  # Nodejs
  app:
    # image: 18.15.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      DB_NAME: ant_home
      DB_USER: root
      DB_PASS: 12345
      DB_HOST: db
    depends_on:
      - db
  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    # Biến
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345
    ports:
      - '5000:80'
    depends_on:
      - db
volumes:
  db_data:
